#ifndef AURORA_UAPI_SYSCALL_NUMBERS_H
#define AURORA_UAPI_SYSCALL_NUMBERS_H

#include <stdint.h>

enum {
    SYSCALL_WRITE_SERIAL = 0U,
    SYSCALL_GET_TICKS = 1U,
    SYSCALL_YIELD = 2U,
    SYSCALL_KMALLOC = 3U,
    SYSCALL_KFREE = 4U,
    SYSCALL_HEAP_USED = 5U,
    SYSCALL_HEAP_TOTAL = 6U,
    SYSCALL_PMM_FREE_PAGES = 7U,
    SYSCALL_GETCHAR = 8U,
    SYSCALL_SLEEP = 9U
};

#endif
